name: Docker push on Docker Hub

env:
    IMAGE_TAG: ${{ github.run_id }}

on: 
    push:
        branches: 
            - main

jobs:
    Push-of-Docker-Image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout of repo
              uses: actions/checkout@v3
            
            - name: Dump GitHub context
              run : echo " Run_id is --- $IMAGE_TAG"  

            #- name: Build of docker image
            # run : |
            #    docker build -t terezabisharyan/simple-cpp-app2:latest .
            #    
            #- name: Push of image on Docker Hub
            #  run : |
            #    docker login -u terezabisharyan -p ${{ secrets.DOCKER_PASSWORD }}    
            #    docker push terezabisharyan/simple-cpp-app2:latest